### ISSUE TITLE
compile class without existing, but referenced, instvar gives strange compile error

### ISSUE THREAD

**Issue by ericwinger** [GemTalk/Rowan#464] opened 2019-01-08 21:15 UTC
1. Create a class A in Rowan with an inst var #foo. 
2. Compile a getter method for foo (or some method that references ``foo``). 
3. In a workspace ecompile  A, replacing the inst var ``foo`` with ``bar`` as such:
```
Object rwSubclass: 'A'
	instVarNames: #( bar)
	classVars: #()
	classInstVars: #()
	poolDictionaries: #()
	category: 'RowanSample1-Core'
	options: #()
```
4. Get strange compile error

![image](https://user-images.githubusercontent.com/36212516/50859025-050f3800-1347-11e9-947a-36725c1c3194.png)

I checked, and a compile error is being sent back from the server.  You can also just remove the referenced instance variable to see the same error.

**Comment by regkrock** [comment] 2019-01-08 21:23
This is also a problem if one has not migrated the class.

Add an instance variable, #newVariable, and do a commit. Then try to remove the #oldVariable. The behavior is the same and it is hard to see what is the source of the problem.

Also, there should be a better message when attempting to remove and instance variable that is referenced. It is not obvious what the root of the problem is.

**Comment by dalehenrich** [comment] 2019-01-08 21:56
@ericwinger, so what is the issue that you are reporting ... AFAICT, this is the error that should be raised when the methods are recompiled and the class is being redefined ... what alternate behavior do you expect?

**Comment by dalehenrich** [comment] 2019-01-08 22:11
after discussion with @ericwinger we'll close this bug in favor of GemTalk/Jadeite#390

**Closed by dalehenrich** 2019-01-08 22:11 UTC
Labels: bug
