### ISSUE TITLE
Adding extension method to Globals class is problematic

### ISSUE THREAD

**Issue by LisaAlmarode** [GemTalk/Rowan#263] opened 2018-07-06 21:10 UTC
It's tricky to add a extension method to a base class in Jadeite. It may not be possible without already having a suitable package setup outside of a Jadeite and/or preexisting in the application. 

Say you create a new package in an existing project (very unlikely to have a SymbolDictionary of Globals), or if you pick an existing package that doesn't already have a SymbolDictionary of Globals.   There's no way in Jadeite to manage the SymbolDictionary of a package

Then you create a category named *packagename, and try to add a method in that category: you get the following error.

If you already have a package with your Globals extensions it would probably work fine. 

a UserDefinedError occurred (error 2318), reason:halt, The extension class named 
'AbstractCharacter' cannot be found in this symbol dictionary (#'SampleSymbolDict'). Packages that extend a class must be loaded into the symbol dictionary in which the class is installed.

UserDefinedError (AbstractException) >> _signalWith: @5 line 25
UserDefinedError (AbstractException) >> signal @2 line 47
RwGsSymbolDictionaryRegistry (Object) >> error: @6 line 7
[] in  ExecBlock0 (RwGsSymbolDictionaryRegistry_Implementation class) >> ensureExtensionClassNamed:existsForPackageNamed:instance: @10 line 8
SymbolDictionary >> at:ifAbsent: @12 line 18
RwGsSymbolDictionaryRegistry_Implementation class >> ensureExtensionClassNamed:existsForPackageNamed:instance: @4 line 5
RwGsSymbolDictionaryRegistry >> ensureExtensionClassNamed:existsForPackageNamed:implementationClass: @2 line 5
RwGsClassExtensionSymbolDictPatch >> installClassExtensionInSystem @27 line 16
[] in  ExecBlock1 (RwGsPatchSet_254) >> installAddedClassExtensions @2 line 3
[] in  ExecBlock1 (Set) >> do: @2 line 11
[] in  ExecBlock2 (KeyValueDictionary) >> keysDo: @2 line 7
KeyValueDictionary >> keysAndValuesDo: @23 line 20
KeyValueDictionary >> keysDo: @2 line 6
Set >> do: @3 line 11
RwGsPatchSet_254 >> installAddedClassExtensions @2 line 3
RwGsPatchSet_254 >> apply @19 line 21
RwGsImage class >> applyModification_254:visitorClass:instanceMigrator: @10 line 9
RwGsImage class >> applyModification_254:instanceMigrator: @8 line 12
RwPrjLoadTool >> _loadProjectSetDefinition_254:instanceMigrator: @17 line 19
[] in  ExecBlock0 (RwPrjLoadTool) >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
RwPrjLoadTool >> _doProjectSetLoad_254:instanceMigrator:originalProjectSet:processedClassNames: @2 line 6
RwPrjLoadTool >> loadProjectSetDefinition:instanceMigrator: @3 line 7
RwPrjLoadTool >> loadProjectSetDefinition: @4 line 4
[] in  ExecBlock2 (RwPrjBrowserTool) >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @46 line 64
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta:inPackageNamed: @24 line 94
RwPrjBrowserTool >> addOrUpdateMethod:inProtocol:forClassNamed:isMeta: @13 line 37
AbstractCharacter class (Behavior) >> rwCompileMethod:category: @9 line 4
[] in  ExecBlock0 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @7 line 7
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
[] in  ExecBlock0 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @2 line 14
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit3x) >> compileMethod:behavior:symbolList:inCategory: @2 line 16
JadeServer64bit32 (JadeServer) >> sbSaveMethod: @12 line 9
JadeServer64bit32 (JadeServer) >> systemBrowserCommand @121 line 40
[] in  ExecBlock0 (JadeServer) >> systemBrowserA: @14 line 10
Time class >> secondsElapsedTime: @5 line 11
Time class >> millisecondsElapsedTime: @2 line 6
JadeServer64bit32 (JadeServer) >> millisecondsElapsedTime: @2 line 3
JadeServer64bit32 (JadeServer) >> systemBrowserA: @2 line 4
JadeServer64bit32 (JadeServer) >> systemBrowser: @3 line 2
[] in  ExecBlock0 (JadeServer64bit) >> systemBrowser: @2 line 4
ExecBlock0 (ExecBlock) >> on:do: @3 line 42
JadeServer64bit32 (JadeServer64bit) >> systemBrowser: @2 line 5
GsNMethod class >> _gsReturnToC @1 line 1

**Comment by dalehenrich** [comment] 2018-11-09 18:59
Aha ... the unit tests for `RwGsSymbolDictionaryRegistry >> ensureExtensionClassNamed:existsForPackageNamed:implementationClass: ` are probably testing a base class that already has extension methods (like Object?) ... now that I understand the issue, let's get if fixed

**Comment by dalehenrich** [comment] 2018-11-10 00:00
there was no test case, but the first test case I added (0b46e96) is passing ... declaring that the package is associated with Globals does work (that is the api that I'm testing)

**Comment by dalehenrich** [comment] 2018-11-10 00:02
... so this does boil down to a jadeite issue and will likely be addressed with GemTalk/Jadeite#270

**Comment by dalehenrich** [comment] 2018-11-13 21:55
@LisaAlmarode ... if the root cause of this bug is the Jadeite GUI (i.e, being able to associate symbol dictionary with a new package) then should be transferred to Jadeite as a bug ... otherwise I need a better test case that exposes a Rowan bug ...

**Comment by LisaAlmarode** [comment] 2018-11-13 22:54
Yes, this is jadeite API - no problem creating extension methods using definition.

**Comment by dalehenrich** [comment] 2018-11-17 17:59
Hit this while creating a test case for Issue #364:
![image](https://user-images.githubusercontent.com/623951/48664119-e4b1b400-ea4e-11e8-8f00-7e8156afe29f.png)
and it is clear that there is a bug in RwPrjBrowserTool>>addOrUpdateMethod:inProtocol:forClassNamed:isMeta: reopening and plan to fix for candidateV1.2 soon ...

**Comment by dalehenrich** [comment] 2018-11-17 18:50
... and [as before](https://github.com/GemTalk/Rowan/issues/263#issuecomment-437532491) once I fixed the test bug, the test passes as it should ... another false alarm:)

**Closed by dalehenrich** 2018-11-17 18:50 UTC
