### ISSUE TITLE
Jadeite - Inspector on characters in iso88599 fails

### ISSUE THREAD

**Issue by regkrock** [GemTalk/Rowan#473] opened 2019-02-26 15:04 UTC
I inspected the following code in Jadeite workspace:

     (ZnCharacterEncoder newForEncoding: 'iso88599') characterDomain

An inspector was opened but when I attempted to drill into the 'dict' instance variable by double clicking on it, an error occurred. The error is shown below:

![image](https://user-images.githubusercontent.com/7550442/53422641-dd833600-39ad-11e9-8fd3-0d03c58d6ff2.png)

**Comment by ericwinger** [comment] 2019-04-23 17:18
@dalehenrich @regkrock ZnCharacterEncoder doesn't exist in my image. Do you have a reproduction case using a base image class?

**Comment by LisaAlmarode** [comment] 2019-08-20 17:22
Inspect: (Set with: (Character withValue: 353))
then double click on "dict".

**Comment by LisaAlmarode** [comment] 2019-08-20 17:27
Closing this since the Jadeite issue is where it will get attention.  Hopefully.

**Closed by LisaAlmarode** 2019-08-20 17:27 UTC
Labels: duplicate
